const ActionTypes = {
  FETCH_POPULAR_MOVIES: "FETCH_POPULAR_MOVIES",
  FETCH_QUERY_MOVIES: "FETCH_QUERY_MOVIES",
  SET_LOADING: "SET_LOADING",
  SET_GENRES: "SET_GENRES",
  FETCH_GENRES_MOVIES: "FETCH_GENRES_MOVIES",
};

export default ActionTypes;
